<?php

/** @var Magento\Framework\View\Element\Template $block */
/** @var Magento\Framework\ViewModel\Reto1 $viewModel */
$viewModel = $block->getViewModel();
$character = $viewModel->getDat();
//$character2 = $viewModel->getUser();
?>

<header class="masthead" style="background-image: url('assets/img/home-bg.jpg')">

    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <img src='<?php echo $this->getViewFileUrl('Omnipro_Reto1::/media/blogimage.png'); ?>' class="w-100 h-100 img-thumbnail" width="100" height="100">
                    <h1>My Espectacular Blog</h1>
                    <span class="subheading">Rafael Pulido - David Delgado</span>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container px-4 px-lg-5">
    <div style="background: rgb(132,132,139);
        background: linear-gradient(90deg, rgba(132,132,139,1) 0%, rgba(173,163,163,0.3284664207479867) 97%);">
        <div class="row gx-4 gx-lg-5 justify-content-center">

            <div class="col-md-10 col-lg-8 col-xl-7">

                <form id="form" enctype="multipart/form-data" method="POST">
                    <br>
                    <div class="mb-3">
                        <h2 for="exampleFormControlInput1" class="post-title">New Blog Post</h2>
                        <input id="title" name="title" class="form-control" type="text" placeholder="Title text" aria-label="default input example" required="true"">
                    </div>
                    <div class=" mb-3">
                        <label for="exampleFormControlTextarea1" class="form-label">Insert Content</label>
                        <textarea id="content" name="content" class="form-control" id="exampleFormControlTextarea1" rows="10" required="true"></textarea>
                    </div>

                    <div class="mb-3">
                        <label for="exampleFormControlInput1" class="form-label">Email address</label>
                        <input id="email" name="email" type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com" required="true">
                    </div>

                    <!--<div>
                        <label for="formFileLg" class="form-label">Subir Imagen</label>
                        <input id="file" name="file" class="form-control form-control-lg" id="formFileLg" type="file">
                       </div>
                    -->

                    <br>

                    <button class="btn btn-secondary">Save Post</button>
                    <br>

                </form>
                <br>
            </div>
        </div>
    </div>

</div>

<!-- Main Content-->

<section class="blog-list px-3 py-5 p-md-5">
    <div class="container">

        <!--//item-->
        <?php foreach ($character as $resulItem) : ?>

            <div style="-webkit-box-shadow: 1px 3px 13px 1px rgba(0,0,0,0.68);
                        -moz-box-shadow: 1px 3px 13px 1px rgba(0,0,0,0.68);
                        box-shadow: 1px 3px 13px 1px rgba(0,0,0,0.68);">
                <div class="item mb-5">
                    <h1 class="title mb-1"><?= $resulItem['title'] ?></h1>
                    <div class="media">
                        <img class="mr-3 img-fluid post-thumb d-none d-md-flex" src="https://s3.amazonaws.com/libapps/accounts/10097/images/blog.png" alt="image">
                        <div class="media-body">
                            <h6 style="text-align: right;"><span class="date"><?= $resulItem['fecha'] ?></span></h6>

                            <p style="font-size: 14px"><?= $resulItem['content'] ?></p>

                            <br>

                            <span class="author">Posted By: <span class="author-name"><?= $resulItem['email'] ?></span></span>
                        </div>
                        <!--//media-body-->
                    </div>
                    <!--//media-->
                </div>
            </div>
        <?php endforeach; ?>

    </div>
</section>


<script type="text/javascript">
    //validar campo vacio
    function validaVacio(valor) {
        valor = valor.replace("&nbsp;", "", " ");
        valor = valor == undefined ? "" : valor;
        if (!valor || 0 === valor.trim().length) {
            return true;
        } else {
            return false;
        }
    }

    //funcion para validar correo
    function validarCorreo(correo) {
        const cor = /^([a-z0-9._-]{5,25})+@[a-z]{3,20}[.]\b[a-z.]{2,8}$/;
        const respuesta = cor.test(correo);
        if (respuesta) {
            return true
        } else {
            return false
        }
    }

    //funcion para validar caracteres especiales
    function validarCaracteres(dato) {

        const car = /^[a-zA-Z0-9á-úÁ-Ú._ *-]$/;
        const respuesta = car.test(dato);
        if (respuesta) {
            return true
        } else {
            return false
        }
    }

    function guardar() {
        object = {
            title: title,
            content: content,
            email: email,
            file: file
        }

        $.post('https://app.bootcamp.test/reto1/index/index', {
            object
        });

        //window.location.replace("https://app.bootcamp.test/reto1");
        document.getElementById("form").reset();

        //envía los datos sinrecargar la página
        e.preventDefault();

        //alert
        return alert("hdgtd");

    }


    require(['jquery', 'jquery/ui'], function($) {
        jQuery(document).ready(function() {

            document.getElementById("form").addEventListener('submit', function(e) {
                //envía los datos sinrecargar la página
                //e.preventDefault();

                const title = document.getElementById('title').value;
                const content = document.getElementById('content').value;
                const email = document.getElementById('email').value;
                //const file = document.getElementById('file').value;

                if (validaVacio(title) || validaVacio(content) || validaVacio(email)) {
                    //alert
                    return $('.alert-modal-content2').alert({
                        title: $.mage.__('Warning'),
                        content: $.mage.__('Warning content'),
                        actions: {
                            always: function() {}
                        }
                    });

                    //redireccioono para que no se me cargue la pagina y vuelva a enviar el formulario 
                    //window.location.replace("https://app.bootcamp.test/reto1");

                }

                if (!validarCorreo(email)) {
                    //alert
                    return $('.alert-modal-content2').alert({
                        title: $.mage.__('Warning'),
                        content: $.mage.__('Warning content'),
                        actions: {
                            always: function() {}
                        }
                    });

                    //redireccioono para que no se me cargue la pagina y vuelva a enviar el formulario 
                    //window.location.replace("https://app.bootcamp.test/reto1");

                }

                if (!validarCaracteres(title) || !validarCaracteres(content) || !validarCaracteres(email)) {
                    //alert
                    return $('.alert-modal-content2').alert({
                        title: $.mage.__('Warning'),
                        content: $.mage.__('Warning content'),
                        actions: {
                            always: function() {}
                        }
                    });

                    //redireccioono para que no se me cargue la pagina y vuelva a enviar el formulario 
                    //window.location.replace("https://app.bootcamp.test/reto1");

                }

                guardar();
                

            })

        });
    });
</script>



<div class="alert-modal-content">
    <p>Se han insertado los datos correctamente</p>
</div>

<div class="alert-modal-content2">
    <p>Por favor inserta todos los datos</p>
</div>